### ISSUE TITLE
Make the header bar floating over the content

### ISSUE THREAD

**Issue by marbetschar** [marbetschar/time-limit#18]
If possible, so we gain the red marked height and the app itself occupies less space on the screen:

![Screenshot from 2020-02-08 11-01-30](https://user-images.githubusercontent.com/392542/74083336-20290b80-4a63-11ea-864d-b73b21e07388.png)

**Comment by marbetschar** [comment]
Seems like `Hdy.ApplicationWindow` has no separate titlebar and one is expected to pack a headerbar inside. So we may gain this height by switching to libhandy.

To keep in mind: libhandy is only available on Odin.

Source: https://developer.puri.sm/projects/libhandy/unstable/HdyApplicationWindow.html

**Comment by marbetschar** [comment]
> - "HdyWindow allows to ... show titlebar above content by putting it into a GtkOverlay instead of GtkBox ..."
> - "HdyApplicationWindow is a GtkApplicationWindow subclass providing the same features as HdyWindow."

https://gnome.pages.gitlab.gnome.org/libhandy/HdyWindow.html

**Comment by hanaral** [comment]
Unless the headerbar is Gala territory, can't you overlay the content over the headerbar?
