### ISSUE TITLE
Add hibernation support to avoid time shifts

### ISSUE THREAD

**Issue by marbetschar** [marbetschar/time-limit#25]
We need to add hibernation support to avoid time shifts if the computer was sent to sleep while a countdown is running.

Right now, if the computer sleeps the countdown simply stops and then it continuous once the computer is awake again. This leads to an unwanted side effect: The desired time limit is shifted by the amount of time the computer was asleep.

**Comment by marbetschar** [comment]
We can use a fix similar to this: https://github.com/elementary/greeter/pull/472

**Comment by marbetschar** [comment]
@vjr I tried to implement your hibernation support logic into my Time Limit app, but for some reason the callback is not fired. Do you have any idea why this does not seem to work? Would be awesome if you can point me into the right direction :)

https://github.com/marbetschar/time-limit/compare/bugfix/hibernation-support

**Comment by vjr** [comment]
Hi! I'm not too familiar with this but can you try sleep (suspend to RAM) instead of hibernate (suspend to disk) and see if that works? The freedesktop docs say the `PrepareForSleep` signal is supposed to trigger for both modes but it's worth a try?

**Comment by marbetschar** [comment]
@vjr thanks for your quick response! I made an error and wrongly named the DBus interface `org.freedesktop.login1.LoginManager` instead of `org.freedesktop.login1.Manager`. After correcting this, your code proposal magically started to work! Thank you so much for pointing me towards to the freedesktop specs!
