### ISSUE TITLE
Change the alert sound for Time Limit?

### ISSUE THREAD

**Issue by internetman420** [marbetschar/time-limit#32]
First, thanks for a simple and great app! It could be perfect to make sure that I remember to hang up my washed clothes etc.

However, if it wont be possible to change the alert sound from the default notification sound this wont help me one bit, i need some ALARMA going on.

Thoughts?

**Comment by marbetschar** [comment]
@internetman420 unfortunately it is not possible to customize the notification sound right now:
https://valadoc.org/gio-2.0/GLib.Notification.html

However I'll keep an eye on this, maybe it will be possible one day.

**Comment by marbetschar** [comment]
_for future reference:_

In order to add support for custom notification sounds, this feature needs to be merged and released into `GLib`: https://gitlab.gnome.org/GNOME/glib/-/issues/1340

**Comment by internetman420** [comment]
> @internetman420 unfortunately it is not possible to customize the notification sound right now:
> https://valadoc.org/gio-2.0/GLib.Notification.html
> 
> However I'll keep an eye on this, maybe it will be possible one day.

Even not with gconf terminal magic? I mean, you can make the Files app dark mode, why not change sound for a specific app?

**Comment by marbetschar** [comment]
😁️ appreciate your enthusiasm, but unfortunately the Time Limit app itself is not responsible for the notifications - it just sends off a notification request to the notification server.

That said, sound customization needs to be added to the notification server itself, which is why I added [this request](https://github.com/elementary/notifications/issues/75) to the brand new notification server which will hopefully released in elementary 6.0

**Comment by internetman420** [comment]
> grin appreciate your enthusiasm, but unfortunately the Time Limit app itself is not responsible for the notifications - it just sends off a notification request to the notification server.
> 
> That said, sound customization needs to be added to the notification server itself, which is why I added [this feature request](https://github.com/elementary/notifications/issues/75) to the brand new notification server which will hopefully be released in elementary 6.0

Cheers! Keep it up!
