### ISSUE TITLE
Transparency on gnome

### ISSUE THREAD

**Issue by gavr123456789** [marbetschar/time-limit#38]
![image](https://user-images.githubusercontent.com/30507409/93667539-5ade3200-fa8f-11ea-8430-b3b3645a39f2.png)
Gnome 3.38
Arch

**Comment by marbetschar** [comment]
Thanks for reporting @gavr123456789! Will look at this while crafting v2.0 which will support Odin. Hopefully this will also fix this issue in GNOME.

**Comment by marbetschar** [comment]
@gavr123456789 any chance you can compile & install the latest master on your end to test whether the fix works for you? Feel free to reopen the issue if the error persists.

**Comment by gavr123456789** [comment]
Okey, will try this evening

**Comment by gavr123456789** [comment]
![image](https://user-images.githubusercontent.com/30507409/95844668-d6ab6180-0d51-11eb-8b7a-3749c1e58d1f.png)
Nice, looking good, ty!
