### ISSUE TITLE
Doubled fast time ticking

### ISSUE THREAD

**Issue by gavr123456789** [marbetschar/time-limit#43]
![Peek 2020-10-15 12-47](https://user-images.githubusercontent.com/30507409/96107154-c081da80-0ee4-11eb-9ba0-10b7c8eb0e1c.gif)
Idk how I did this.

**Comment by marbetschar** [comment]
I'm not quite sure I understand the issue here. Can you please elaborate?

**Comment by gavr123456789** [comment]
Look at the seconds timer. It ticks 2 at a time.
