### ISSUE TITLE
Usability problem, close "button" is too small

### ISSUE THREAD

**Issue by QWxleA** [marbetschar/time-limit#62]
![Time Limit_001](https://user-images.githubusercontent.com/24763887/132116977-b1631e1c-4dc3-41fc-bc1a-ba13b78f1200.png)

The closing icon is fairly small, and I keep missing it, thus pausing the timer, instead of minimizing the app. The "landing space" around the "X" should be way bigger. (Cheap) trackpads are not very accurate :-(

**Comment by marbetschar** [comment]
Fixed in v3
